### ISSUE TITLE
Docker部署的兰空图床怎么升级

### ISSUE THREAD

**Issue by flow2000** [HalcyonAzure/lsky-pro-docker#12]
![image](https://user-images.githubusercontent.com/67251012/198036982-988b2226-2ea4-4c72-b407-6e5ba9c34d59.png)
如题，按照教程备份数据后，如果我删掉容器再拉取新镜像会不会出错？

**Comment by HalcyonAzure** [comment]
如果只是要升级的话，只需要直接在`Lsky-Pro`的 "管理后台"->"系统设置“ 最下方的 "系统升级"检查更新即可

如果说要备份数据，以我的`docker-compose.yaml`的配置为例：

```yaml
...
  lsky-pro:
    ...
    volumes:
      - $PWD/html:/var/www/html
    ...
  mysql-lsky:
    ...
    volumes:
      - $PWD/mysql/data:/var/lib/mysql
      - $PWD/mysql/conf:/etc/mysql
      - $PWD/mysql/log:/var/log/mysql
    ...
...
```
那么我只需要备份了在`$PWD`目录下的`docker-compose.yaml`，`mysql`和`html`以后就可以在新机器上通过`docker-compose up -d`来恢复了。同理，如果没有配置`mysql`的话则只需要备份`html`文件夹内`Lsky-Pro`的内容目录即可

`Dockerfile`本身的安装逻辑是检查你挂在的`Lsky-Pro`安装目录（比如所谓的`html`）下是否已经有`index.php`文件，也就是你是否已经完成过`Lsky-Pro`的安装，如果不存在这个文件则会帮你将最新的`Lsky-Pro`仓库拉取的代码进行安装。如果存在这个文件则表明你的`Lsky-Pro`已经成功安装过，则不会将最新的仓库代码覆盖掉你老的环境，只起到一个提供`php`环境的作用，此时如果要升级就是在后台直接升级就行
