### ISSUE TITLE
使用nginx反代后访问域名无法正常使用

### ISSUE THREAD

**Issue by IIllIIIlll** [HalcyonAzure/lsky-pro-docker#25]
核心问题：访问反代后的域名会自动添加一个端口号。

---

我将`lsky pro`和`nginx proxy manager`部署在同一个docker网络中，`lsky pro`的`docker-compose.yml`内容如下：

```yaml
version: '3.9'
services:
  lsky-pro:
    image: halcyonazure/lsky-pro-docker:latest
    container_name: lsky-pro
    restart: unless-stopped
    ports:
      - 8089:8089
    expose:
      - 8089
    environment:
      - WEB_PORT=8089
    volumes:
      - ./data:/var/www/html
    networks:
      - default

  lsky-db:
    image: postgres:latest
    container_name: lsky-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: lsky
      POSTGRES_PASSWORD: lsky
      POSTGRES_DB: lsky
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - default

networks:
  default:
    name: nginx-proxy
    external: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16

```

我在`nginx proxy manager`的高级参数中添加了如下内容：

```
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
```

当我访问我的域名的时候（例如`https://pic.mydomain.com`），会自动跳转到`https://pic.momoai.me:8089/install`。但是假如我直接访问内网ip，例如`http://192.168..5.40:8089`，是能够正常进入安装步骤的。

请问为什么会自动跳转到端口号呢？

补充信息：

我最开始配置的时候，是先使用局域网ip配置完成后再反向代理的，之后访问域名会加载出部分画面，查看控制台发现很多请求发往`https://pic.mydomain.com:8089`，我怀疑是作者的`apache`设置原因，但是我并不熟悉其设置，作者能提供一个思路，或者分析出其他原因吗？

万分感谢！
