### ISSUE TITLE
启动镜像会报 Could not reliably determine the server's fully qualified domain name 错误

### ISSUE THREAD

**Issue by YGXB-net** [HalcyonAzure/lsky-pro-docker#26]
## 环境

- docker镜像为最新构建的镜像
- 使用系统为：Debian 11

## 问题

使用 `docker compose up` 启动镜像后会报错，然后无法启动，具体报错信息如下

```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.21.0.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.21.0.2. Set the 'ServerName' directive globally to suppress this message
[Sun May 07 01:37:34.435506 2023] [mpm_prefork:notice] [pid 16] AH00163: Apache/2.4.56 (Debian) PHP/8.1.18 configured -- resuming normal operations
[Sun May 07 01:37:34.442329 2023] [core:notice] [pid 16] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
```

![截图](https://user-images.githubusercontent.com/87907576/236653833-1cc41a77-c586-4f08-897b-11ccaf26f245.png)

## 配置

`docker-compose.yml` 文件如下

```
services:
  lsky:
    image: halcyonazure/lsky-pro-docker:latest
    restart: unless-stopped
    volumes:
      - /data/lsky/web:/var/www/html/
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    name: nginx-proxy-manager_nginx-proxy
    external: true
```

PS：非常感谢作者大大的项目，希望这个问题可以得到解决
